# Generated by Django 5.0.4 on 2024-09-17 23:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=255)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paiement', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fichier_pdf', models.FileField(upload_to='factures/')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_stock', models.PositiveIntegerField()),
                ('seuil_critique', models.PositiveIntegerField()),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.boutique')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.categorieproduit')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employe', 'Employé')], max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], max_length=10)),
                ('date_de_connexion', models.DateTimeField(blank=True, null=True)),
                ('boutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.boutique')),
                ('groups', models.ManyToManyField(blank=True, related_name='utilisateur_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='utilisateur_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField()),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.boutique')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_remboursement', models.DateTimeField(auto_now_add=True)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.client')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateTimeField(auto_now_add=True)),
                ('type_rapport', models.CharField(choices=[('journalier', 'Journalier'), ('mensuel', 'Mensuel')], max_length=20)),
                ('total_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefice_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthentificationApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_notification', models.DateTimeField(auto_now_add=True)),
                ('type_notification', models.CharField(choices=[('connexion', 'Connexion'), ('sortie_produit', 'Sortie produit'), ('stock_critique', 'Stock critique')], max_length=20)),
                ('message', models.TextField()),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthentificationApp.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('vente', 'Vente'), ('entree', 'Entrée produit'), ('modification', 'Modification stock')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details_action', models.TextField()),
                ('boutique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthentificationApp.boutique')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthentificationApp.produit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthentificationApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_paiement', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Crédit')], default='cash', max_length=10)),
                ('rabais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthentificationApp.client')),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vente_facture', to='AuthentificationApp.facture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='AuthentificationApp.vente'),
        ),
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_produit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.vente')),
            ],
        ),
    ]
