# Generated by Django 5.0.4 on 2024-09-22 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
