# Generated by Django 5.0.4 on 2024-09-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0002_produit_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='boutique',
        ),
    ]
