# Generated by Django 5.0.4 on 2024-09-23 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0004_remove_vente_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='facture',
        ),
    ]
