# Generated by Django 5.0.4 on 2024-09-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0005_remove_vente_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venteproduit',
            name='total_produit',
        ),
        migrations.AlterField(
            model_name='vente',
            name='rabais',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
