# Generated by Django 5.0.4 on 2024-09-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0006_remove_venteproduit_total_produit_alter_vente_rabais'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteproduit',
            name='total_produit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
