# Generated by Django 5.0.4 on 2024-09-24 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0007_venteproduit_total_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='date_facture',
        ),
        migrations.AlterField(
            model_name='facture',
            name='vente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.vente'),
        ),
    ]
