# Generated by Django 5.0.4 on 2024-09-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0008_remove_facture_date_facture_alter_facture_vente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prix_vente',
            new_name='prix_unitaire',
        ),
        migrations.RenameField(
            model_name='venteproduit',
            old_name='quantite',
            new_name='quantite_vendue',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='rabais',
        ),
        migrations.RemoveField(
            model_name='venteproduit',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='venteproduit',
            name='total_produit',
        ),
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='nombre_vente_journee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vente',
            name='total_encaisse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='total_rabais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='prix_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='rabais_produit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
