# Generated by Django 5.0.4 on 2024-09-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0009_rename_prix_vente_produit_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='utilisateur',
        ),
    ]
