# Generated by Django 5.0.4 on 2024-09-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0010_remove_vente_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venteproduit',
            name='vente',
        ),
    ]
