# Generated by Django 5.0.4 on 2024-09-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0011_remove_venteproduit_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='venteproduit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.venteproduit'),
            preserve_default=False,
        ),
    ]
