# Generated by Django 5.0.4 on 2024-09-28 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0013_remove_vente_venteproduit_venteproduit_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
