# Generated by Django 5.1 on 2024-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0014_vente_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='CNIB',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
