# Generated by Django 5.1 on 2024-10-02 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0015_client_cnib'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdVenduMois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.produit')),
            ],
            options={
                'unique_together': {('produit', 'mois')},
            },
        ),
    ]
