# Generated by Django 5.1 on 2024-10-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0016_prodvendumois'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodvendumois',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prodvendumois',
            name='total_encaisse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
