# Generated by Django 5.1 on 2024-10-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0017_prodvendumois_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthentificationApp.vente')),
            ],
        ),
    ]
