# Generated by Django 5.1 on 2024-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0018_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='etait_credits',
            field=models.BooleanField(default=False),
        ),
    ]
