# Generated by Django 5.1 on 2024-10-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0019_vente_etait_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='pdf',
            field=models.FileField(default=0, upload_to='factures/'),
            preserve_default=False,
        ),
    ]
